var docHistory = {
    'CAMBIAR_FOTO_FIRMA': 7,
    'ADMINISTRAR_PERFIL': 8,
    'CAMBIAR_CONTRASENIA': 9,
    'EXPORTAR_MIS_DATOS': 10,
    'ELIMINAR_MI_CUENTA': 11,
    'ACEPTAR_CONSULTA': 12,
    'DECLINAR_CONSULTA': 13,
    'VER_PERFIL_PACIENTE': 14,
    'GUARDAR_INFO_PACIENTE': 15,
    'ACTUALIZAR_DATOS_PACIENTE': 16,
    'ACTUALIZAR_ANTECEDENTES': 17,
    'VER_HISTORIAL_CLINICO': 18,
    'GUARDAR_DATOS_CONSULTA': 19,
    'FINALIZAR_CONSULTA': 20,
    'CLACIFICAR_CONSULTA': 21,
    'GENERAR_LLAMADA_MANUAL': 22,
    'ACTUALIZAR_CALENDARIO_CITAS_PROGRAMDAS': 23,
    'MI_CUENTA': 24,
    'VER_HISTORIAL_ANTECEDENTES': 25
}


